fusesource/jansi

- jansi/src/main/java/org/fusesource/jansi/AnsiConsole.java
If stderr was redirected to a file but stdout was not, the ANSI escape codes were present in that file, which is bad.
> Check isatty() separately for stdout and stderr

- jansi/src/main/java/org/fusesource/jansi/AnsiConsole.java
Cygwin's default terminal, mintty, is able to process ANSI sequences
although it's running on Windows. So treat Cygwin as a Unix variant.
> Detect Cygwin, including the MSYS(2) forks

- jansi/src/main/java/org/fusesource/jansi/Ansi.java
- jansi/src/test/java/org/fusesource/jansi/AnsiRendererTest.java
Add missing Ansi fluent APIs: fgRed(), fgBrightRed(), and so on.
> Add missing Ansi fluent APIs.

- jansi/src/main/java/org/fusesource/jansi/AnsiConsole.java
- jansi/src/main/java/org/fusesource/jansi/AnsiOutputStream.java
- jansi/src/main/java/org/fusesource/jansi/AnsiRenderer.java
- jansi/src/main/java/org/fusesource/jansi/HtmlAnsiOutputStream.java
- jansi/src/main/java/org/fusesource/jansi/WindowsAnsiOutputStream.java
- jansi/src/test/java/org/fusesource/jansi/AnsiConsoleExample.java
- jansi/src/test/java/org/fusesource/jansi/AnsiConsoleExample2.java
This pull request is focused on resolving occurrences of Sonar rules
squid:SwitchLastCaseIsDefaultCheck - "switch" statements should end with a "default" clause.
squid:S1197 - Array designators "[]" should be on the type, not the variable.
squid:S1118 - Utility classes should not have public constructors.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:SwitchLastCaseIsDefaultCheck
https://dev.eclipse.org/sonar/rules/show/squid:S1197
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
George Kankava
> Multiple code improvements - squid:SwitchLastCaseIsDefaultCheck, squid:S1197, squid:S1118

- jansi/src/main/java/org/fusesource/jansi/Ansi.java
- jansi/src/main/java/org/fusesource/jansi/AnsiConsole.java
- jansi/src/main/java/org/fusesource/jansi/AnsiOutputStream.java
- jansi/src/main/java/org/fusesource/jansi/AnsiRenderWriter.java
- jansi/src/main/java/org/fusesource/jansi/AnsiRenderer.java
- jansi/src/main/java/org/fusesource/jansi/AnsiString.java
- jansi/src/main/java/org/fusesource/jansi/HtmlAnsiOutputStream.java
- jansi/src/main/java/org/fusesource/jansi/WindowsAnsiOutputStream.java
- jansi/src/test/java/org/fusesource/jansi/AnsiConsoleExample.java
- jansi/src/test/java/org/fusesource/jansi/AnsiConsoleExample2.java
- jansi/src/test/java/org/fusesource/jansi/AnsiRenderWriterTest.java
- jansi/src/test/java/org/fusesource/jansi/AnsiRendererTest.java
- jansi/src/test/java/org/fusesource/jansi/AnsiStringTest.java
- jansi/src/test/java/org/fusesource/jansi/AnsiTest.java
- jansi/src/test/java/org/fusesource/jansi/HtmlAnsiOutputStreamTest.java
based on IDEA 2016 default profile (I think).
I did disable javadoc comment formatting else the license headers (which are presently javadocs) get reformatted.  Header comment should probably be changed to multi-line single-star comment instead of javadoc double-star comment to avoid problems.
I left imports asis, default configuration seems to want to use * imports and I'm not sure that is what you really want.  There are at least a few unused imports that could be removed.
There are also a few other turds I noticed like unneeded ';' in a few places but I left those alone for now too.
> normalize formatting using default idea settings

- jansi/src/main/java/org/fusesource/jansi/AnsiConsole.java
When the native library cannot be loaded, AnsiConsole fails to initialize throwing an UnsatisfiedLinkError.
> java.lang.UnsatisfiedLinkError when native library is not found.

- jansi/src/main/java/org/fusesource/jansi/Ansi.java
ansi(), ie support NoAnsi
currently, using these static methods display ANSI codes even if Ansi is disabled, and this is quite surprising
> make ansi(int) and ansi(StringBuilder) static methods consistent with

- jansi/src/main/java/org/fusesource/jansi/AnsiConsole.java
When trying to start Karaf under Solaris or ARM (raspberry), it hangs with an `UnsatisifedLinkError`. This error is caused by the fact the bundle `jline-2.14.2.jar` contains and uses classes and native libraries from `jansi`. The native library is obviously not essentially required on Unix-style systems, and the `jansi` code already tries to handle the absence of a native library, but still fails at class initialization.
It would be great to do a `jansi` release and include it in `jline` in order to update and fix in Karaf.
> Deal with UnsatisfiedLinkError

- jansi/src/main/java/org/fusesource/jansi/WindowsAnsiOutputStream.java
See https://github.com/fusesource/jansi/issues/69 for information on this PR and [this comment](https://github.com/gradle/gradle/issues/882#issuecomment-270267902) for the reason behind the fix.
> Avoid `WindowsAnsiOutputStream.processCursorDown` overflow on Y axis

- jansi-website/pom.xml
- jansi-website/src/community/site.page
I attached to scm-publish:publish-scm goal to install phase to avoid deploy since it also deploys pom.xml to ossrh repository, but the phase can of course be changed
> use scm-publish plugin to deploy site to gh-pages

- jansi/src/main/java/org/fusesource/jansi/AnsiOutputStream.java
- jansi/src/test/java/org/fusesource/jansi/HtmlAnsiOutputStreamTest.java
Some terminals (xterm) supports two different 'character sets' ('G0' and
'G1'), which can be switched with 'SI' (shift in, '\017') and 'SO'
(shift out, '\016'). Each character set can be configured separately
and can be chosen from a list of pre-defined sets like 'ASCII Set' and
'Special Graphics'.
Running `TERM=xterm tput sgr0` to reset the terminal returns an escape
sequence starting with 'ESC ( 0', which selects the 'ASCII Set' for
'G0'. This currently is not understood by the Jenkins AnsiColor plugin.
Filter out those sequences, as they otherwise clutter the output.
<https://www.in-ulm.de/~mascheck/various/alternate_charset/> has a nice
description for characters sets
This is issue <https://github.com/fusesource/jansi/issues/29>, a
upstream port of …
> Filter out escape sequence 'character set' select

- jansi/src/main/java/org/fusesource/jansi/WindowsAnsiOutputStream.java
Fix regression issue introduced in Jansi 1.16.
The escape sequence **ESC[1;30m** (change to bright black foreground) cannot be rendered correctly since version 1.16 due to the second rendition parameter **30** overwrite the change made by the first parameter **1**, resulting incorrectly in normal black.
May also fix issue #94.
> Correct support for the bright colors on windows - regression fix

- jansi/src/main/java/org/fusesource/jansi/AnsiConsole.java
- jansi/src/main/java/org/fusesource/jansi/AnsiPrintStream.java
- jansi/src/main/java/org/fusesource/jansi/FilterPrintStream.java
- jansi/src/main/java/org/fusesource/jansi/WindowsAnsiPrintStream.java
- jansi/src/test/java/org/fusesource/jansi/FilterPrintStreamTest.java
should fix issue #93 this this avoids any guess on encoding and let original PrintStream do its job
test code from #88 is also committed to ease testing
> use PrintStream to avoid encoding issues

- jansi/src/main/java/org/fusesource/jansi/Ansi.java
- jansi/src/main/java/org/fusesource/jansi/AnsiOutputStream.java
- jansi/src/main/java/org/fusesource/jansi/AnsiPrintStream.java
- jansi/src/main/java/org/fusesource/jansi/AnsiRenderer.java
- jansi/src/main/java/org/fusesource/jansi/AnsiString.java
- jansi/src/main/java/org/fusesource/jansi/FilterPrintStream.java
avoid so many conversions of 
char -> to String -> getChars() -> copy chars -> foreach char -> to String -> getChars ... 
also use bigger buffer... as printed log line usually got more than 50 chars.. 
not 16 as default in StringBuilder constructor (with 16 chars, you can write "Hello World !!!!" )
> enhance memory usage using buffer, or avoiding alloc

- src/download.page
Maven.org responds with a 501 now to HTTP links and wants https used instead.
https://github.com/fusesource/jansi/issues/170
> Change to https links to address issue 170

- Makefile
I was really chuffed to find that you've been using my FreeBSD cross-build container. I built the container to meet my personal needs, but I'm happy you've been able to find use in it as well. However, I built it without much familiarity with Docker in general, and in particular, without knowledge of [the `WORKDIR` instruction](https://docs.docker.com/engine/reference/builder/#workdir). I've just updated my Dockerfile to specify a working directory, and this PR adds support for its use when building the FreeBSD natives.
> Use the FreeBSD container working directory

- src/main/java/org/fusesource/jansi/Ansi.java
- src/test/java/org/fusesource/jansi/AnsiTest.java
Adds a new method "apply" to the Ansi class. This is especially useful when used with lambdas. Applying other functions to the Ansi class is now possible without breaking out of the fluent API flow. This is best shown with the following example:
Before:
```
Ansi ansi = Ansi.ansi().fgRed();
complexFunction(ansi);
ansi.reset();
```
Now:
```
Ansi ansi = Ansi.ansi().fgRed().apply(this::complexFunction).reset();
```
> Add Ansi.apply method

- pom.xml
- src/main/java/org/fusesource/jansi/Ansi.java
- src/test/java/org/fusesource/jansi/AnsiTest.java
Generalizes cursor movement such as `cursorUp`, `cursorDown`, ... to negative values, which move the cursor in the opposite direction.
Also adds a new method `cursorMove` that moves the cursor in horizontal and vertical direction at once.
> Generalize cursor movement

- src/main/java/org/fusesource/jansi/io/AnsiProcessor.java
- src/test/java/org/fusesource/jansi/io/AnsiOutputStreamTest.java
Currently `jansi` doesn't handle the sequence `ESC[0;38m`. This PR fixes that and adds a test.
A similar approach has been implemented in Jenkins `ansicolor-plugin` for some time, where the issue has been brought up [by a user in a bug ticket](https://github.com/jenkinsci/ansicolor-plugin/issues/158#issuecomment-616801975).
I am not entirely sure what that sequence is supposed to do (haven't found it in any documentation) but using it in shell doesn't render any special characters/effects so I guess `jansi` should behave the same.
> Handle SGRs with multiple options

- src/main/java/org/fusesource/jansi/internal/OSInfo.java
Since aarch64 is same as arm64, we can simply reference this arch to arm64.
> Add aarch64 support, fix #219

- Makefile.common
@gnodet Please have a look. Just a simple oversight.
> Add missing space in SunOS-sparcv9_CCFLAGS

- pom.xml
This PR adds the moditect maven plugin to the build. This includes a `module-info.class` in a multi-release jar.
The capability this allows is for users to use jansi with jlink without configuration. Its also just a thing that needs to happen for downstream dependencies like jline to do the same.
> Add module-info through moditect

- src/main/java/org/fusesource/jansi/AnsiRenderer.java
- src/test/java/org/fusesource/jansi/AnsiRendererTest.java
This fixes a possible unwrapped StringIndexOutOfBoundException in src/main/java/org/fusesource/jansi/AnsiRenderer.java.
In [line 85](https://github.com/arthurscchan/jansi/blob/master/src/main/java/org/fusesource/jansi/AnsiRenderer.java#L85), [line 95](https://github.com/arthurscchan/jansi/blob/master/src/main/java/org/fusesource/jansi/AnsiRenderer.java#L95) and [line 101](https://github.com/arthurscchan/jansi/blob/master/src/main/java/org/fusesource/jansi/AnsiRenderer.java#L101) of the AnsiRenderer class. The method tries to determine the necessary index j and k for doing a substring operation on the input string. If the input string is malformed, it could cause j larger than k and result in StringIndexOutOfBoundException. For example, if the EndToken appears before the BeginToken, or …
> Fix invalid string input

- src/main/java/org/fusesource/jansi/AnsiConsole.java
- src/main/java/org/fusesource/jansi/ffm/AnsiConsoleSupportFfm.java
- src/main/java/org/fusesource/jansi/ffm/Kernel32.java
- src/main/java/org/fusesource/jansi/ffm/PosixCLibrary.java
- src/main/java/org/fusesource/jansi/ffm/WindowsAnsiProcessor.java
- src/main/java/org/fusesource/jansi/ffm/WindowsCLibrary.java
- src/main/java/org/fusesource/jansi/internal/OSInfo.java
The FFM backend appears to be untested and will crash when using it, I'm trying to solve these problems.
* Avoid lookup `ioctl` and `isatty` on Windows;
* Make `SYMBOL_LOOKUP` initialized earlier to avoid NPE
* Fix wrong alignment;
* Load Kernel32;
* Fix incorrect type conversion;
* Impl CLibrary for Windows;
* Fix string encoding;
There are more issues waiting to be fixed, WIP.
> Fix FFM backend on Windows

- src/main/java/org/fusesource/jansi/Ansi.java
- src/main/java/org/fusesource/jansi/AnsiConsole.java
- src/main/java/org/fusesource/jansi/AnsiMain.java
- src/main/java/org/fusesource/jansi/internal/JansiLoader.java
- src/main/java/org/fusesource/jansi/internal/OSInfo.java
- src/main/java/org/fusesource/jansi/io/AnsiOutputStream.java
- src/main/java/org/fusesource/jansi/io/FastBufferedOutputStream.java
- src/test/java/org/fusesource/jansi/AnsiTest.java
- src/test/java/org/fusesource/jansi/EncodingTest.java
- src/test/java/org/fusesource/jansi/io/AnsiOutputStreamTest.java
Use Java 8 features for some harmless cleaning.
> Modernize code

- src/main/java/org/fusesource/jansi/AnsiConsole.java
- src/main/java/org/fusesource/jansi/AnsiMain.java
- src/main/java/org/fusesource/jansi/WindowsSupport.java
- src/main/java/org/fusesource/jansi/internal/AnsiConsoleSupport.java
- src/main/java/org/fusesource/jansi/internal/AnsiConsoleSupportHolder.java
- src/main/java/org/fusesource/jansi/internal/ffm/AnsiConsoleSupportFfm.java
- src/main/java/org/fusesource/jansi/internal/ffm/AnsiConsoleSupportImpl.java
- src/main/java/org/fusesource/jansi/internal/ffm/Kernel32.java
- src/main/java/org/fusesource/jansi/internal/ffm/PosixCLibrary.java
- src/main/java/org/fusesource/jansi/internal/ffm/WindowsAnsiProcessor.java
- src/main/java/org/fusesource/jansi/internal/ffm/WindowsCLibrary.java
- src/main/java/org/fusesource/jansi/internal/jni/AnsiConsoleSupportImpl.java
- src/main/java/org/fusesource/jansi/internal/jni/AnsiConsoleSupportJni.java
- src/test/java/org/fusesource/jansi/AnsiTest.java
* Move the classes related to AnsiConsoleSupport to `org.fusesource.jansi.internal`;
* Using static final variables to cache `CLibrary` and `Kernel32` in `AnsiConsoleSupportHolder`;
The purpose is to avoid duplicate creation of `CLibrary` and `Kernel32`, and make it easier to be inlined by the JIT compiler;
* Delete `JANSI_PROVIDERS_DEFAULT`,  because I think there should be a more flexible selection strategy by default rather than just relying on a list;
* Make ffm not selected by default when the jansi module does not have native access enabled;
This prevents the JDK from printing warning messages in stderr.
> Refactoring AnsiConsoleSupport

- pom.xml
- src/main/java/org/fusesource/jansi/internal/AnsiConsoleSupport.java
- src/main/java/org/fusesource/jansi/internal/AnsiConsoleSupportHolder.java
- src/main/java/org/fusesource/jansi/internal/NativeImageFeature.java
- src/main/java/org/fusesource/jansi/internal/OSInfo.java
- src/main/java/org/fusesource/jansi/internal/ffm/AnsiConsoleSupportImpl.java
- src/main/java/org/fusesource/jansi/internal/ffm/Kernel32.java
- src/main/java/org/fusesource/jansi/internal/ffm/NativeImageDowncallRegister.java
- src/main/java/org/fusesource/jansi/internal/ffm/NativeImageFeatures.java
- src/main/java/org/fusesource/jansi/internal/ffm/PosixCLibrary.java
- src/main/java/org/fusesource/jansi/internal/jni/AnsiConsoleSupportImpl.java
- src/main/resources/META-INF/native-image/jansi/native-image.properties
- src/main/resources/META-INF/native-image/jansi/resource-config.json
See: https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/foreign-interface/
This PR provides FFM support for native-image.
Since FFM support in both JDK 21 and GraalVM is in preview, this PR is also experimental until GraalVM provides stable support for FFM.
Users need to provide the following options to the native-image tool to enable FFM support: 
```
--enable-preview --enable-native-access=org.fusesource.jansi -Djansi.providers=ffm
```
If jansi is on the class path instead of the module path, replace `org.fusesource.jansi` with `ALL-UNNAMED`.
This PR is working, but there seems to be some glitch that I still need to look into
> Support using FFM in native-image
